Invoicing edit
killbill/killbill-docs pull request #118
Opened 2020-05-03 16:26 UTC by jdmooney

Corrected typos and expanded some descriptions

2020-05-04 07:13 UTC, pierre requested changes

2020-05-04 07:13 UTC, pierre commented on userguide/subscription/includes/invoicing-usage.adoc
> +Currently it is considered an error to delete past usage data in these past 2 periods. IF this occurs, the invoicing system throws an error and prevents invoicing from happening correctly. If the lat
Typo: `IF`

2020-05-04 07:13 UTC, pierre commented on userguide/subscription/includes/invoicing-usage.adoc
> +If we were instead using the `TOP_TIER` policy, all usage of `cell-phone-minutes` would be billed at the tier 2 price (20) for a total of 2400, so the aggregate amount reported would be 2500.
It's great to have added an additional example!

2020-05-04 21:31 UTC, sbrossie approved these changes
Looks good - we could merge after you have addressed the few comments from Pierre.

2020-05-05 00:26 UTC, jdmooney commented on userguide/subscription/includes/invoicing-usage.adoc
> +Currently it is considered an error to delete past usage data in these past 2 periods. IF this occurs, the invoicing system throws an error and prevents invoicing from happening correctly. If the lat
corrected

2020-05-05 01:27 UTC, merged