How-Tos for multi-tier
killbill/killbill-docs pull request #468
Opened 2023-02-10 17:13 UTC by jdmooney

This PR creates How-To files for setting up a multi-tier system, with separate files for maintenance and adding a certificate.

2023-02-10 22:23 UTC, sbrossie requested changes
@jdmooney  Could you review the warnings, in particular it points to a set of sections for code blocks that seem incorrectly formatted, as per [doc](https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/) should be:


```
[source,bash]
----
```

2023-02-10 22:26 UTC, sbrossie commented
Also, do we already have the links in place to point to these new docs, or will this come in a subsequent PR?

2023-02-11 14:50 UTC, jdmooney commented
I think I fixed the code block links now. Still trying to get it right for Asciidoc.

As for links to these docs, I am wondering the same thing. I don't think we have a plan yet. @reshmabidikar @FlowWriter do you have any ideas?

2023-02-13 11:08 UTC, reshmabidikar commented
> As for links to these docs, I am wondering the same thing. I don't think we have a plan yet. @reshmabidikar @FlowWriter do you have any ideas?

I believe Mary had suggested the following structure a while back:
```
Possible Reorganization:
Kill Bill on AWS
	Introduction
	Tutorials
		Single-Tier Demo
	How-To
		Setup an AWS Account
		Install Kill Bill using Cloud Formation
		Install Kill Bill using the Multi-Tier Option
		Install Kill Bill in a Serverless Container
		Add a Certificate
		Use the Simple Email Service (SES)
		Use Datadog to analyze metrics
		Use New Relic to Analyze Metrics
		Use CloudWatch to Analyze Metrics
		Use Rollbar to Track Errors
		Use Sentry to Track Errors
	Reference
		The AWS AMI
		The CloudFormation Template
		Kill Bill AWS Configuration
```

This [google doc](https://docs.google.com/document/d/1EX_Vyazg8W7mnqEuizohXOm7lPAJhNRp_9KRi2Ufh4I/edit#heading=h.5ioadz32ya8e) has the details.

2023-02-13 23:03 UTC, sbrossie commented on userguide/aws/how-tos/maintain-a-multi-tier-system.adoc
> +```[source,bash]
@jdmooney Looks like there is one more to fix ^^^

2023-03-13 09:59 UTC, reshmabidikar commented
Doesn't this PR contain the same changes as in https://github.com/killbill/killbill-docs/pull/475?

2023-03-31 17:13 UTC, jdmooney commented on userguide/aws/how-tos/maintain-a-multi-tier-system.adoc
> +```[source,bash]
fixed

2023-04-03 03:34 UTC, reshmabidikar commented
These changes are also included in #475. So closing this PR.

2023-04-03 03:34 UTC, closed without merging